## Algorithms

### Sorting algos
- https://visualgo.net/en/sorting?slide=1

In [2]:
import numpy as np

In [30]:
## Bubble sort

def bubble_sort(array):
      
    sorted_index = len(array)
    while sorted_index > 0:
        for i in range(len(array)-1):
        #Compare two numbers 
            left = i
            right = left+1

            #If right number is smaller than left number, switch places
            if array[left]>array[right]:
                new_right = array[left]
                array[left] = array[right]
                array[right] = new_right

        sorted_index -= 1 
        print(f'Sorted index {sorted_index}')

        #TODO more effient with pointers? 

    return array

In [31]:
#Test bubble sort 
array_test = [2,1,0]

sorted_array_test = bubble_sort(array_test)
sorted_array_test

Sorted index 2
Sorted index 1
Sorted index 0


[0, 1, 2]

In [38]:
from numpy.random import default_rng

rng = default_rng()
array = rng.choice(10, size=10, replace=False)
print(array)
sorted_array = bubble_sort(array)
sorted_array

[7 8 1 4 6 0 9 5 2 3]
Sorted index 9
Sorted index 8
Sorted index 7
Sorted index 6
Sorted index 5
Sorted index 4
Sorted index 3
Sorted index 2
Sorted index 1
Sorted index 0


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
def selection_sort(array): 

    #linear search
    sorted_idx = 0
    print(len(array))

    #for each element in nonsorted, check if it is smaller than minimum. if it is set as miniumum
    while sorted_idx < len(array):
        print(f'Sorted idx {sorted_idx}')

        min = array[sorted_idx]
        min_idx = sorted_idx

        for i in range(sorted_idx+1, len(array)):

            if array[i]< min: 
                min = array[i]
                min_idx = i 

            #print(min)

        #Swap min with leftmost 
        swap = array[sorted_idx]
        #insert min
        array[sorted_idx] = array[min_idx]

        #insert swap 
        array[min_idx] = swap
        sorted_idx +=1
        
    return array 

In [25]:
from numpy.random import default_rng

rng = default_rng()
array = rng.choice(10, size=10, replace=False)
print(array)

sorted_array = selection_sort(array)
sorted_array


[0 3 7 1 6 2 8 5 9 4]
10
Sorted idx 0
Sorted idx 1
Sorted idx 2
Sorted idx 3
Sorted idx 4
Sorted idx 5
Sorted idx 6
Sorted idx 7
Sorted idx 8
Sorted idx 9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
test_array = np.array([3,1,2])

for element in test_array:
    print(element)

3
1
2


In [38]:
def insertion_sort_attempt(array):

    #set the leftmost number to sorted 
    sorted_idx = 0 

    #We are going to go through the whole array with our operation
    while sorted_idx<(len(array)-1):
        
        #check if the next number is less than the sorted number, if it is swap the two numbers
        if array[sorted_idx]>array[sorted_idx+1]:
            swap = array[sorted_idx]
            array[sorted_idx] = array[sorted_idx+1]
            array[sorted_idx +1] = swap

            #Then check if the now left number is smaller than the number to its left
            swapped_idx = sorted_idx

            while swapped_idx>0 and array[swapped_idx]<array[swapped_idx-1]: #TODO: different moving backwards implementation
                #Put the leftmost number in the placeholder
                swap = array[swapped_idx-1]
                #insert the right number into the left index
                array[swapped_idx-1] = array[swapped_idx]
                #insert the swap number into the rightmost array
                array[swapped_idx]=swap

                #Iterate the swapped index by -1 to check for the next number
                swapped_idx -=1

                print(f'swapped_idx {swapped_idx}')
                print(f'Array in moving sorted number backwards {array}')

        #If the right number is larger than the left, just iterate the sorted idx
        else:
            pass

        ##   Code does the same thing twice, comparing an element to element in idx-1. 
        # The while loop achieves the same, the if stateement not necessary
        # Instead of holding one number as key throughout, we end up doing twice as many swapping operations 
        # by continuously swapping while searching backwards in the array for the position

        print(f'array {array}')
        
        #Consider all numbers left of the current index fully sorted, and iterate the sorted_idx with 1
        sorted_idx +=1 

        print(f'Sorted index {sorted_idx}')
    #Set new sorted

    return array

In [46]:
def insertion_sort(array):

    #in round i look at the i-th element 
    #Start with i = 1

    #insert this in its right place among the i-1 elements
    #FIXME adds n to running time
    for i in range(1, len(array)):
    
        #do this by storing x[i] in a variable key and 
        key = array[i]
        j = i
        #While key is larger than
        # moving x[i-1], x[i-2] and so on one “to the right” until an element x[j-1] is encountered with x[j-1] < key (or we reach the start of the array)
        #FIXME adds n per n loop
        while j>0 and key<array[j-1]:   

            #move the number in array[j-1] to position j 
            array[j] = array[j-1]

            j -=1
            print(f'j: {j}, interim array: {array}')
    
        #I then insert key at position j (or the start) 
        array[j] = key

    return array

- Is there a performance difference between insertion sort attempt and insertion sort from the slides? 


In [47]:
import numpy as np 
test_array= np.array([3,2,1])

insertion_sort(test_array)

j: 0, interim array: [3 3 1]
j: 1, interim array: [2 3 3]
j: 0, interim array: [2 2 3]


array([1, 2, 3])

In [40]:
from numpy.random import default_rng

rng = default_rng()
array = rng.choice(10, size=10, replace=False)
print(array)

sorted_array = insertion_sort(array)
sorted_array

[2 9 3 0 7 1 4 5 6 8]
array [2 9 3 0 7 1 4 5 6 8]
Sorted index 1
array [2 3 9 0 7 1 4 5 6 8]
Sorted index 2
swapped_idx 1
Array in moving sorted number backwards [2 0 3 9 7 1 4 5 6 8]
swapped_idx 0
Array in moving sorted number backwards [0 2 3 9 7 1 4 5 6 8]
array [0 2 3 9 7 1 4 5 6 8]
Sorted index 3
array [0 2 3 7 9 1 4 5 6 8]
Sorted index 4
swapped_idx 3
Array in moving sorted number backwards [0 2 3 1 7 9 4 5 6 8]
swapped_idx 2
Array in moving sorted number backwards [0 2 1 3 7 9 4 5 6 8]
swapped_idx 1
Array in moving sorted number backwards [0 1 2 3 7 9 4 5 6 8]
array [0 1 2 3 7 9 4 5 6 8]
Sorted index 5
swapped_idx 4
Array in moving sorted number backwards [0 1 2 3 4 7 9 5 6 8]
array [0 1 2 3 4 7 9 5 6 8]
Sorted index 6
swapped_idx 5
Array in moving sorted number backwards [0 1 2 3 4 5 7 9 6 8]
array [0 1 2 3 4 5 7 9 6 8]
Sorted index 7
swapped_idx 6
Array in moving sorted number backwards [0 1 2 3 4 5 6 7 9 8]
array [0 1 2 3 4 5 6 7 9 8]
Sorted index 8
array [0 1 2 3 4 5 6 7 8 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
## Merge sort
#https://www.geeksforgeeks.org/merge-sort/

import numpy as np

def merge(a,b):
    
    n = (len(a)+len(b))
    c = np.empty([n])
    print(f'n :{n} len c {len(c)}')
    #a
    i = 0
    #b
    j = 0
    k = 0

    while i<len(a) and j<len(b):
        #Insert the smallest of numbers at the i/j th position into the output array
        if a[i]<b[j]:
            c[k]= int(a[i])
            i+=1 
            print(f'iterating i {i}')
        else:
            c[k] = int(b[j])
            j+=1
            print(f'iterating j {j}')

        k+=1 

    #When at the end of array, copy remaining from other into c 
    if (i+1)>len(a):
        print(f'Came to end of a at i {i}, n {n}')
        c[k:]=b[j:]

    elif (j+1)>len(b):
        print(f'Came to end of b at j {j}, n {n}')
        c[k:] = a[i:]
    
    else:
        pass 

    print(f' c: {c} ')

    return c

def merge_sort(array):
    
    print(f"Got array {array}")
    #Base case 
    if len(array)<=1: 
        return array
    
    # Split array 
    n = len(array)
    half_n = int(n/2)
    print(f'n: {n}, half_n {half_n}')

    #One recursive call on each half
    first_half = array[:half_n]
    second_half = array[half_n:]

    print(f'first_half : {first_half} \n second_half: {second_half}')

    #First recursive call
    a = merge_sort(first_half)

    print(f'a: {a}')

    #Second recursive call 
    b = merge_sort(second_half)

    print(f'b: {b}')

    # Sort each half recursively 
    
    # Merge subarrays a and b
    c = merge(a, b)

    return c


In [87]:
from numpy.random import default_rng

rng = default_rng()
array = rng.choice(10, size=10, replace=False)
print(array)


sorted_array = merge_sort(array)
sorted_array

[3 0 7 6 4 1 9 8 5 2]
Got array [3 0 7 6 4 1 9 8 5 2]
n: 10, half_n 5
first_half : [3 0 7 6 4] 
 second_half: [1 9 8 5 2]
Got array [3 0 7 6 4]
n: 5, half_n 2
first_half : [3 0] 
 second_half: [7 6 4]
Got array [3 0]
n: 2, half_n 1
first_half : [3] 
 second_half: [0]
Got array [3]
a: [3]
Got array [0]
b: [0]
n :2 len c 2
iterating j 1
Came to end of b at j 1, n 2
 c: [0. 3.] 
a: [0. 3.]
Got array [7 6 4]
n: 3, half_n 1
first_half : [7] 
 second_half: [6 4]
Got array [7]
a: [7]
Got array [6 4]
n: 2, half_n 1
first_half : [6] 
 second_half: [4]
Got array [6]
a: [6]
Got array [4]
b: [4]
n :2 len c 2
iterating j 1
Came to end of b at j 1, n 2
 c: [4. 6.] 
b: [4. 6.]
n :3 len c 3
iterating j 1
iterating j 2
Came to end of b at j 2, n 3
 c: [4. 6. 7.] 
b: [4. 6. 7.]
n :5 len c 5
iterating i 1
iterating i 2
Came to end of a at i 2, n 5
 c: [0. 3. 4. 6. 7.] 
a: [0. 3. 4. 6. 7.]
Got array [1 9 8 5 2]
n: 5, half_n 2
first_half : [1 9] 
 second_half: [8 5 2]
Got array [1 9]
n: 2, half_n 1
first_h

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
np.empty([10])

array([9.9e-324, 4.9e-324, 2.5e-323, 3.5e-323, 0.0e+000, 4.4e-323,
       1.5e-323, 3.0e-323, 2.0e-323, 4.0e-323])